### PR TITLE
Add Time mod

### PR DESCRIPTION
**Pull request by MatMercer**
A mod that enables you to change the world time in the client side.

I didn't noticed that you created more commits into your master branch, that's why there are merge errors.

### CODE REVIEW

**Review by Alexander01998 — CHANGES_REQUESTED** [review]
This cannot be merged with a broken patch file. Please do either of the following:
- Fix the patch by updating your fork and then re-running `update-patch.bat` with the latest data.
- Remove your changes to the patch and instead type them into a comment on GitHub so that I can apply them manually.

**Comment by MatMercer** [comment]
Sure, I'll see what I can do.

**Comment by MatMercer** [comment]
The mod was changed, it is weather mod now.
New pull request is [here](https://github.com/Wurst-Imperium/Wurst-MC-1.10/pull/34).

**Comment by MattSturgeon** [comment]
@MrAnyone It would be good to have the weather mod **and** the time mod, if possible :)

**Pull request closed without merging**
