### PR TITLE
Add InventoryMove mod

### PR DESCRIPTION
**Pull request by ghost**
Add a simple mod which allows you to walk while guis (e.g. your inventory) are open

### CODE REVIEW

**Comment by CisBetter** [comment]
Isn't that the same as MenuWalk?

**Comment by ghost** [comment]
Oops, it is. I didn't notice that module.

Should we keep it like it is right now (hardcoded) or replace it against my code (softcoded)?

**Comment by MatMercer** [comment]
If you change a keybind (like, 'D' key to 'right arrow' key) while this mod is running does the keybind keeps bypassing the GUI?

**Comment by ghost** [comment]
@MatMercer Yes, it will

**Pull request closed without merging**
