### PR TITLE
Fix `leave` command

### PR DESCRIPTION
**Pull request by DesWurstes**
Not crashing anymore.

### CODE REVIEW

**Comment by DesWurstes** [comment]
Reason?

**Comment by Alexander01998** [comment]
I just updated AutoLeave so that the settings are being accessed through fields.

**Comment by DesWurstes** [comment]
If you don't want to fix its bugs, why don't you remove the useless lines?

**Comment by DesWurstes** [comment]
https://github.com/Wurst-Imperium/Wurst-MC-1.11/blob/ff06aee7f05714e6b662956274254cf4af4a5863/src/tk/wurst_client/features/commands/LeaveCmd.java#L44-L48

**Pull request closed without merging**
