### PR TITLE
Feature: NoOverlay

### PR DESCRIPTION
**Pull request by CisBetter**
NoOverlay blocks the overlays of pumpkins, water, fire, and lava
(standard in modern clients). If Wurst already contains this mod let me
know :smile:
## Some screen shots (all with a pumpkin on the head):

**underwater**

**in lava**

**standing in fire**

Signed-off-by: CisBetter CisBetter@users.noreply.github.com

### CODE REVIEW

**Comment by MatMercer** [comment]
Cool! I tried to make a mod like this sometime ago but at the time I wasn't  too familiar with Java and I was unable to find how Minecraft rendered the overlays effects.
If you would like to answer, how do you managed to find all the overlays in the code? I mean over inspection it's quite hard to find what you need. Do you use debug or only the global search from Eclipse.

Thanks by the way.

**Comment by CisBetter** [comment]
First: Thank you for your positive response :smiley:

Second:
I've used the following method to find the overlays.
1. Click 'Search' in the main toolbar: 
2. To find the water-overlay (blur) search for "`*water*breathing*`" (This potion effect reduces the blur, NOTE: I am using File Search for this).
   
3. In the following result
   
   we can already see that the rendering function has to be in the directory "client/renderer".
   As there is only one file containing this string (EntityRenderer.java) we should take a closer look at it...
4. This is the second match in this file. 
   

`fogDensity` looks promising so lets try to modify that (the changes are already visible in the above screenshot).... And... **It works!**
5. To block the pumpkin we will take a look at minecraft's resources. The `textures` folder contains `pumpkinblur.png`:

6. Search for that:

The only result that comes up:

7. In the same file there is this function call:

8. **Changing that removes the pumpkin overlay...**

I hope this helps you :grin:

`-CisBetter`

**Comment by MatMercer** [comment]
Oh I understood! Thanks for the detailed answer.

**Review by Alexander01998 — CHANGES_REQUESTED** [review]
Please sign the [CLA](https://cla-assistant.io/Wurst-Imperium/Wurst-MC-1.10?pullRequest=47).

**Review by Alexander01998 — APPROVED** [review]

**Pull request merged**
